# 1. Base image
FROM node:22.14.0

# 2. Install pnpm
RUN npm install -g pnpm

# 3. Set working directory
WORKDIR /bsoblog-prod

# 4. Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --strict-peer-dependencies=false


# 5. Copy source code
COPY . .

# 6. Build the app
RUN pnpm build

# 7. Set environment to production
ENV NODE_ENV=production

# 8. Start app
CMD ["pnpm", "start"]
