services:
  db:
    image: pgvector/pgvector:pg17
    container_name: dev-blog-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dev-blog-redis
    restart: always
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-blog-pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dev-backend-go-app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: ${APP_ENV}
      GIN_MODE: ${GIN_MODE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  extractor:
    build:
      context: ./extractor
      dockerfile: Dockerfile
    container_name: dev-blog-extractor-python-app
    restart: always
    ports:
      - "5002:5002"

volumes:
  postgres_data:
