# Use the official Node.js image as the base image
FROM node:18-bullseye

# Set the working directory inside the container
WORKDIR /bsoblog-dev

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build the Next.js application
RUN npm run build

# Start the Next.js application
CMD ["npm", "start"]
