FROM golang:1.24.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o app ./cmd/server


# Stage 2: runtime
FROM debian:bookworm-slim

WORKDIR /app

# Copy compiled binary
COPY --from=builder /app/app .

# Copy keys
RUN mkdir -p /keys
COPY keys/blogPublicAccess.pem /keys/

# Copy .env
COPY .env .env

# Prepare log directory
RUN mkdir -p logs && touch logs/app.log

EXPOSE 8088
CMD ["./app"]
