FROM golang:1.24.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o app ./cmd/server


# Use same OS family to avoid glibc mismatch
FROM debian:bookworm-slim

WORKDIR /app

# Create keys directory
RUN mkdir -p /keys

# Copy keys from your local machine
COPY keys/blogPublicAccess.pem /keys/

COPY --from=builder /app/app .

EXPOSE 8088
CMD ["./app"]
