FROM golang:latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/cespare/reflex@latest

EXPOSE 8088

WORKDIR /app/cmd/server

CMD ["reflex", "-r", "\\.go$", "--", "go", "run", "."]
